version: '3'
services:
  web:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - rainloop-code:/var/www/html
      links:
        - rainloop
  rainloop:
      image: rainloop:test
      volumes:
        - rainloop-code:/var/www/html
        - ./rainloop-data:/var/www/html/data
volumes:
  rainloop-code:
